version: "3"
services:
  www:
      build:
          context: .
          dockerfile: ./Dockerfile.www
      environment:
          MYSQL_DATABASE: myDb
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
          MYSQL_ROOT_USER: root
      ports:
          - 8088:80
      volumes:
          - ../www:/var/www/html/
      networks:
          - default
  test:
      build:
          context: .
          dockerfile: ./Dockerfile.codeception
      environment:
          MYSQL_DATABASE: myDb
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
          MYSQL_ROOT_USER: root
      volumes:
          - ../test:/var/www/test
          - ../www:/var/www/html
      networks:
          - default
  db:
      image: mariadb
      ports: 
          - 3306:3306
      environment:
          MYSQL_DATABASE: myDb
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
          MYSQL_ROOT_USER: root
      volumes:
          - ./dbInit:/docker-entrypoint-initdb.d
      networks:
          - default
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
          - 8081:80
      environment:
          MYSQL_USER: user
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: test
      networks:
          - default
  selenium-hub:
    image: selenium/hub:3.141.59-europium
    container_name: selenium-hub
    networks:
        - default
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome:3.141.59-europium
    shm_size: '2gb'
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
  firefox:
    image: selenium/node-firefox:3.141.59-europium
    shm_size: '2gb'
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
